export const AUDIT_KEY_TRANSLATION: Record<string, string> = {
  responsible_user_id: "responsable",
  responsable_id: "responsable",
  category_id: "categoría",
  categoria_id: "categoría",
  hotel_id: "hotel",
  region_id: "región",
  kpi_id: "kpi",
  business_unit_id: "unidad de negocio",
  sales_channel_id: "canal de ventas",
  marketing_campaign_id: "campaña",
  commercial_team_id: "equipo comercial",
  campaign_id: "campaña",
  status: "estado",
  estado: "estado",
  formula: "fórmula",
  measurement_unit: "unidad de medida",
  unidad_medida: "unidad de medida",
  frequency: "frecuencia",
  frecuencia: "frecuencia",
  info_source: "fuente de información",
  fuente_informacion: "fuente de información",
  indicator_type: "tipo de indicador",
  tipo_indicador: "tipo de indicador",
  version: "versión",
  version_actual: "versión actual",
  name: "nombre",
  nombre: "nombre",
  code: "código",
  codigo: "código",
  description: "descripción",
  descripcion: "descripción",
  responsible_area: "área responsable",
  area_responsable: "área responsable",
  alert_id: "alerta",
  commitment_date: "fecha de compromiso",
  fecha_compromiso: "fecha de compromiso",
  responsible: "responsable (texto)",
  titulo: "título",
  entidad_id: "id entidad",
  activo: "activo",
  meta: "meta",
  valor_real: "valor real",
  valor_meta: "valor meta",
  fuente: "fuente",
  rol: "rol",
  email: "correo",
  activa: "activa",
  endpoint_url: "URL endpoint",
  sistema_tipo: "tipo de sistema",
};

export function formatAuditKey(key: string): string {
  return AUDIT_KEY_TRANSLATION[key] ?? key.replace(/_/g, " ");
}
