export {
  hasPermissionInList as hasPermission,
  canManageKpisFromList as canManageKpis,
  canViewKpisFromList as canViewKpis,
  canExportReportsFromList as canExportReports,
  canImportFromList as canImport,
  canManageIntegrationsFromList as canManageIntegrations,
  canConfigureMetasFromList as canConfigureMetas,
  canManageActionPlansFromList as canManageActionPlans,
  canManageCatalogFromList as canManageCatalog,
  canAccessSeguridadUi,
  canAccessCatalogoUi,
  canManageUsers,
  canCreateKpis,
  canEditKpis,
} from "./role-matrix";
